spring.application.name=api
server.port=8080

# MySQL Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dam_disaster_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_password_here}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
